In [2]:
import torch
from torch import nn
print(torch.cuda.is_available())
#查看gpu是否可用

True


In [3]:
#查看gpu数量
torch.cuda.device_count()

1

In [4]:
#查看当前gpu索引
torch.cuda.current_device()

0

In [5]:
#根据索引查看GPU的名字
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4060 Laptop GPU'

tensor的gpu计算

In [6]:
#默认情况下tensor会被在存在内存上，所以每次打印tensor的时候看不到gpu相关
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [7]:
#使用.cuda()可以将cpu上的tensor转换（复制）到gpu上。（如果有多块gpu，使用（i）来表示第i块
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [8]:
#tensor的device属性来查看该tensor所在的设备
x.device

device(type='cuda', index=0)

In [10]:
#可以在创建的时候就指定设备
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# x = torch.tensor([1,2,3],device = device)
#或者是
x = torch.tensor([1,2,3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [11]:
#如果是对在gpu上的数据及逆行运算，那么结果还是存放在gpu上
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [12]:
#存储在不同位置的数据不能直接进行计算
z = y+x.cpu()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

模型的gpu计算

pytorch的模型也可以通过.cuda转换到gpu上

In [14]:
net = nn.Linear(3,1)
list(net.parameters())[0].device

device(type='cpu')

In [15]:
#转到GPU上
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [16]:
#要保证模型和输入的tensor都在同意设备上，否则会报错
x = torch.rand(2,3).cuda()
net(x)

tensor([[1.0184],
        [1.4626]], device='cuda:0', grad_fn=<AddmmBackward0>)

summary  
本节的内容分成两部分：tensor到gpu上  and   模型到gpu上  
tensor到gpu上：  
.cuda()  
或者  
``` Python
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x.to(device)
```
模型到cuda上  
.cuda()