In [2]:
#numpy数据对象：ndarray
import numpy as np

In [8]:
#创建一个ndarray对象：numpy.array(object,dtype=None,copy=True,oder=None,subok=False,ndmin=0)
#参数依次是：
# object：里面要放的数组/数列
# dytype：数组元素的数据类型
# copy：是否需要赋值
# order：创建数组的样式
# subok：默认返回一个与基类类型一致的数组
# ndmin：指定生成数组的最小维度
a = np.array([1,2,3])
print(a)
b = np.array([[1,2],[3,4]])
print(b)
c = np.array([1,2,3,4],ndmin=2)
print(c)
d = np.array([1,2,3,4],dtype = complex)
print(d)

[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [15]:
#numpy.dtype(object,align,copy)
dt = np.dtype(np.int32)
print(dt)
#int8,int16,int32,int64可以用'i1',i2','i4','i8'代替
dt = np.dtype('i4')
print(dt)

int32
int32


In [29]:
#numpy数组的属性：ndim（秩），shape（维度）size（元素个数），dtype（元素类型），itemsize（元素大小）
#flags（内存布局信息），real（元素实部），image（元素虚部），data（实际存储数组元素的缓冲区）
a = np.arange(24)#0到23
print(a)
b = a.reshape(2,4,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [36]:
#ndim
print(a.ndim)
print(b.ndim)
#shape
print(a.shape)
print(b.shape)
#size
print(a.size)
print(b.size)
#dtype
print(a.dtype)
print(b.dtype)
#itemsize
print(a.itemsize)
print(b.itemsize)
#flags
print(a.flags)

1
3
(24,)
(2, 4, 3)
24
24
int32
int32
4
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [40]:
#创建数组的其他方式
#numpy.empty(shape,dtype=float,erder='C'),创建一个指定形状和数据类型且未初始化的数组
a = np.empty([3,2],int)
print(a)
#numpy.zeros(shape,dtypr=float,order='C')元素0来填充
a = np.zeros([3,2],int)
print(a)
#numpy.ones(shape,dtype,order)
a = np.ones([2,4,2,],float)
print(a)
#numpy.zeros_like(a,dtype,order,subok,shape)
b = np.zeros_like(a,int)
print(b)
#numpy.ones_like同理


[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [45]:
#从已有的数组创建数组
#numpy.asarray(a,dtype,order),将a转换为ndarray类型，a可以是列表元组等等
a = [1,2,3]
ndarray = np.asarray(a,int)
print(ndarray)
b = (1,2,3)
ndarray = np.asarray(b,float)
print(ndarray)
c = [(1,2,3),(2,4)]
ndarray = np.asarray(c,dtype = tuple)
print(c)

[1 2 3]
[1. 2. 3.]
[(1, 2, 3), (2, 4)]


In [61]:
#numpy.frombuffer(buffer,dtype,count=-1,offset=0)
#实现动态数组，接受buffer输入参数，一流的形式读入转化为ndarray格式
s = b"hello world"
a = np.frombuffer(s,dtype='S1')
print(a)


[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [62]:
#numpy.fromiter(iterable,dtype,count=-1)
#从可迭代对象中建立ndarray，返回一维数组
list = range(5)
it = iter(list)
x = np.fromiter(it,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [66]:
#numpy.arrange(start,stop,step,dtype)
x = np.arange(5)
print(x)
x = np.arange(5,step=2)
print(x)
x = np.arange(5,step=2,dtype=float)
print(x)

[0 1 2 3 4]
[0 2 4]
[0. 2. 4.]


In [71]:
#numpy.linspace(start,stop,num=50,endpoint=True,restep=False,dtypr=None)
#创建一个一维数组，是由等差数列构成
# （起始值，终止值，要生成的等步长的样本数量，是否包含终止值，是否显示间距，数据类型）?
x = np.linspace(1,10,10)
print(x)
x = np.linspace(1,1,10,dtype=int)
print(x)
x = np.linspace(1,10,9,endpoint=False)
print(x)
x = np.linspace(1,10,10,retstep=True)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1 1 1 1 1 1 1 1 1 1]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [73]:
#numpy.logspace(start,stop,num=50,endpoint=True,base=10.0,dtype)
#base:取对数的时候log的下标
#序列的终止值为：base**stop
#创建一个等比数列
a= np.logspace(1.0,2.0,num=10)
print(a)
a = np.logspace(00,9,10,base=2)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [77]:
#切片和索引
#slice：切片
a = np.arange(10)
s = slice(2,7,2)#素银从2到7，间隔为2
print(s)
print(a[s])
#就相当于
print(a[2:7:2])

slice(2, 7, 2)
[2 4 6]
[2 4 6]


In [82]:
#高级索引
#获取（0，0）（1，0）（2，0）位置的元素
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [83]:
# 布尔索引
y = x[x>5]
print(y)

[6]
